### ISSUE TITLE
PHP Warning:  preg_replace(): Compilation failed: invalid range in character class at offset 39

### ISSUE THREAD

**Issue by gtirepo** [weDevsOfficial/wp-user-frontend#912]
PHP Warning:  preg_replace(): Compilation failed: invalid range in character class at offset 39 in /home/iwantacode/public_html/wp-content/plugins/wp-user-frontend-pro/includes/libs/Emogrifier.php on line 1294

Code for lines 1291 to 1295:
$roughXpath = '//' . preg_replace(
array_keys($this->xPathRules),
$this->xPathRules,
$trimmedLowercaseSelector
);

Apparently this may be due to PHP7.3 (Escape - character so regex works on PHP 7.3)

**Comment by ediamin** [comment]
@gtirepo Thanks for reporting the bug. Would you please explain a bit more, exactly when this warning occurs? From your log, I can understand that it relates to email. But when do you see this?

**Comment by gtirepo** [comment]
@ediamin I seem to have responded in the incorrect area. This WARNING appears every day when an email is sent to a user informing them that their Subscription Pack has expired

**Comment by hasinur1997** [comment]
Couldn't find the issue.
